### ISSUE TITLE
2018 support

### ISSUE THREAD

**Issue by MadsTheEngineer** [snowe2010/solarized-jetbrains#4]
I really love the Solarized themes, but for work I need to use stable versions of Rider which for now means 2018.3.4 is the newest possible installation.
Would it be possible to support 2018 versions of JetBrains products?

**Comment by Guanaco77** [comment]
It's not possible because the custom UI Themes is a new feature appeared with the 2019.1 release.

You can use this ([https://github.com/jkaving/intellij-colors-solarized](https://github.com/jkaving/intellij-colors-solarized)) for earlier version. But it's only change your editor and not all your appearance.
